include:
  - board: seeeduino_xiao_ble
    shield: iurii_left
  - board: seeeduino_xiao_ble
    shield: iurii_right
  - board: seeeduino_xiao_ble
    shield: iurii_test
  - board: seeeduino_xiao_ble
    shield: iurii_test_right
